= */usr/local* for _NixOS_

The */usr/local* scheme devised here should give you complete, unpatched
GCC suites that you can use without wrappers, outside the _Nix_
environment. Only _glibc_ and _libxcrypt_ are used from within _NixOS_
(unless you arrange it otherwise).

The */usr/local* is mounted and unmounted by a systemd service. There
is no magic to this. It is simply init scripts that you can modify to
your liking.

To keep the */usr/local* very clean and endlessly modifiable, packages
are _not_ installed with *make install* commands, but with *make
install DESTDIR=/some/staged/install/place* commands. The binaries can
be made into tarballs, which in turn can be saved in repositories,
caches, the _Nix_ store, etc. One way or another, they end up in their
own directories. (In the example given here, each ends up in its own
_btrfs_ subvolume.) These directories are then overlayed on top of
each other, along with a ‘core’ containing such things as a slightly
modified copy of the current system _glibc_. The overlay filesystem is
mounted readonly at */usr/local*.

The runtime loader for the */usr/local* is *pkgs.nix-ld*, with
*NIX_LD_LIBRARY_PATH* set to */usr/local/lib64:/usr/local/lib* and
possibly including other subdirectories within the */usr/local* and
one’s */home*. Hardcoded runpaths are not used.footnote:[Mixing this
use of *pkgs.nix-ld* with other uses is an exercise for the
reader. For a most extreme example, one could install all the
libraries needed for an foreign executable into the */usr/local*,
instead of using any libraries but _glibc_ and _libxcrypt_ from the
_Nix_ store.]

***

To set up your own */usr/local*, you can try starting with the binary
packages at
https://sourceforge.net/projects/chemoelectric-nixos/files/usr-local-v1/
There are hashes and digital signatures for these packages in the
*hashes-and-signatures* subdirectory. You can get sources for these
packages at any good GNU mirror, such as https://ftp.wayne.edu/

The */usr/local* is set up mostly by my _NixOS_ configuration. In the
*etc-nixos-example* subdirectory, I provide snippets from the _NixOS_
configuration at the time of this writing. I have left out some
details, such as configuration code to enable *nix-ld* and create
mount points, and _Home Manager_ code to set
*NIX_LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib* and add
*/usr/local/bin* to my *PATH*.

I have the packages hosted on a local webserver and automatically
unpacked into individual _btrfs_ subvolumes. This saves me effort in
rearranging how I have things set up. One could simply unpack the
packages by hand, however, and put them where one wishes them to be.

The packages are a _GCC 11_ toolchain. Every language is included
except Brig (which was being removed and is not in _GCC 12_). The
reason for choosing _GCC 11_ is that this is the last version of _GCC_
in which the implementation of _D_ is written in _C++_ instead of in
_D_ itself. Thus this is the best starting point for building later
versions of _GCC_.

The packages have been built with the */usr/local* itself. My
*/usr/local* was bootstrapped from humble beginnings, starting with
*pkgs.gnat-bootstrap11*, modified _Nixpkgs_ code, ad hoc abuse of the
_GCC_ build process, overlay filesystems and chroots, and (most
importantly) powerful magic potions and incantations.footnote:[One
could also have started the bootstrap with packages built on a regular
Linux distro. The heroics were necessary only to find a way to start
with the broken compilers that come with _NixOS_ itself. It seemed at
one time this would be necessary. However, now that I have other means
to create binaries and host them online, I am not sure there is any
reason to start with *pkgs.gnat-bootstrap11* for my other projects.]

From here on, I think you are on your own. Have fun!
